// Code generated by capnpc-go. DO NOT EDIT.

package sandstormhttpbridge

import (
	context "context"
	grain "zenhack.net/go/sandstorm/capnp/grain"
	identity "zenhack.net/go/sandstorm/capnp/identity"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type SandstormHttpBridge struct{ Client *capnp.Client }

// SandstormHttpBridge_TypeID is the unique identifier for the type SandstormHttpBridge.
const SandstormHttpBridge_TypeID = 0xad678f0d09bdd98a

func (c SandstormHttpBridge) GetSandstormApi(ctx context.Context, params func(SandstormHttpBridge_getSandstormApi_Params) error) (SandstormHttpBridge_getSandstormApi_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSandstormApi",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSandstormApi_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return SandstormHttpBridge_getSandstormApi_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSessionContext(ctx context.Context, params func(SandstormHttpBridge_getSessionContext_Params) error) (SandstormHttpBridge_getSessionContext_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionContext",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSessionContext_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return SandstormHttpBridge_getSessionContext_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSavedIdentity(ctx context.Context, params func(SandstormHttpBridge_getSavedIdentity_Params) error) (SandstormHttpBridge_getSavedIdentity_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSavedIdentity",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSavedIdentity_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return SandstormHttpBridge_getSavedIdentity_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) SaveIdentity(ctx context.Context, params func(SandstormHttpBridge_saveIdentity_Params) error) (SandstormHttpBridge_saveIdentity_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      3,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "saveIdentity",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_saveIdentity_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return SandstormHttpBridge_saveIdentity_Results_Future{Future: ans.Future()}, release
}

// A SandstormHttpBridge_Server is a SandstormHttpBridge with a local implementation.
type SandstormHttpBridge_Server interface {
	GetSandstormApi(context.Context, SandstormHttpBridge_getSandstormApi) error

	GetSessionContext(context.Context, SandstormHttpBridge_getSessionContext) error

	GetSavedIdentity(context.Context, SandstormHttpBridge_getSavedIdentity) error

	SaveIdentity(context.Context, SandstormHttpBridge_saveIdentity) error
}

// SandstormHttpBridge_NewServer creates a new Server from an implementation of SandstormHttpBridge_Server.
func SandstormHttpBridge_NewServer(s SandstormHttpBridge_Server, policy *server.Policy) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(SandstormHttpBridge_Methods(nil, s), s, c, policy)
}

// SandstormHttpBridge_ServerToClient creates a new Client from an implementation of SandstormHttpBridge_Server.
// The caller is responsible for calling Release on the returned Client.
func SandstormHttpBridge_ServerToClient(s SandstormHttpBridge_Server, policy *server.Policy) SandstormHttpBridge {
	return SandstormHttpBridge{Client: capnp.NewClient(SandstormHttpBridge_NewServer(s, policy))}
}

// SandstormHttpBridge_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func SandstormHttpBridge_Methods(methods []server.Method, s SandstormHttpBridge_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSandstormApi",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSandstormApi(ctx, SandstormHttpBridge_getSandstormApi{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionContext",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSessionContext(ctx, SandstormHttpBridge_getSessionContext{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSavedIdentity",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSavedIdentity(ctx, SandstormHttpBridge_getSavedIdentity{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      3,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "saveIdentity",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.SaveIdentity(ctx, SandstormHttpBridge_saveIdentity{call})
		},
	})

	return methods
}

// SandstormHttpBridge_getSandstormApi holds the state for a server call to SandstormHttpBridge.getSandstormApi.
// See server.Call for documentation.
type SandstormHttpBridge_getSandstormApi struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSandstormApi) Args() SandstormHttpBridge_getSandstormApi_Params {
	return SandstormHttpBridge_getSandstormApi_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSandstormApi) AllocResults() (SandstormHttpBridge_getSandstormApi_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results{Struct: r}, err
}

// SandstormHttpBridge_getSessionContext holds the state for a server call to SandstormHttpBridge.getSessionContext.
// See server.Call for documentation.
type SandstormHttpBridge_getSessionContext struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSessionContext) Args() SandstormHttpBridge_getSessionContext_Params {
	return SandstormHttpBridge_getSessionContext_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSessionContext) AllocResults() (SandstormHttpBridge_getSessionContext_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results{Struct: r}, err
}

// SandstormHttpBridge_getSavedIdentity holds the state for a server call to SandstormHttpBridge.getSavedIdentity.
// See server.Call for documentation.
type SandstormHttpBridge_getSavedIdentity struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSavedIdentity) Args() SandstormHttpBridge_getSavedIdentity_Params {
	return SandstormHttpBridge_getSavedIdentity_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSavedIdentity) AllocResults() (SandstormHttpBridge_getSavedIdentity_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results{Struct: r}, err
}

// SandstormHttpBridge_saveIdentity holds the state for a server call to SandstormHttpBridge.saveIdentity.
// See server.Call for documentation.
type SandstormHttpBridge_saveIdentity struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_saveIdentity) Args() SandstormHttpBridge_saveIdentity_Params {
	return SandstormHttpBridge_saveIdentity_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_saveIdentity) AllocResults() (SandstormHttpBridge_saveIdentity_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results{Struct: r}, err
}

type SandstormHttpBridge_getSandstormApi_Params struct{ capnp.Struct }

// SandstormHttpBridge_getSandstormApi_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSandstormApi_Params.
const SandstormHttpBridge_getSandstormApi_Params_TypeID = 0x86d490c59f64c564

func NewSandstormHttpBridge_getSandstormApi_Params(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_getSandstormApi_Params{st}, err
}

func NewRootSandstormHttpBridge_getSandstormApi_Params(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_getSandstormApi_Params{st}, err
}

func ReadRootSandstormHttpBridge_getSandstormApi_Params(msg *capnp.Message) (SandstormHttpBridge_getSandstormApi_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSandstormApi_Params{root.Struct()}, err
}

func (s SandstormHttpBridge_getSandstormApi_Params) String() string {
	str, _ := text.Marshal(0x86d490c59f64c564, s.Struct)
	return str
}

// SandstormHttpBridge_getSandstormApi_Params_List is a list of SandstormHttpBridge_getSandstormApi_Params.
type SandstormHttpBridge_getSandstormApi_Params_List struct{ capnp.List }

// NewSandstormHttpBridge_getSandstormApi_Params creates a new list of SandstormHttpBridge_getSandstormApi_Params.
func NewSandstormHttpBridge_getSandstormApi_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSandstormApi_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return SandstormHttpBridge_getSandstormApi_Params_List{l}, err
}

func (s SandstormHttpBridge_getSandstormApi_Params_List) At(i int) SandstormHttpBridge_getSandstormApi_Params {
	return SandstormHttpBridge_getSandstormApi_Params{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSandstormApi_Params_List) Set(i int, v SandstormHttpBridge_getSandstormApi_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSandstormApi_Params_List) String() string {
	str, _ := text.MarshalList(0x86d490c59f64c564, s.List)
	return str
}

// SandstormHttpBridge_getSandstormApi_Params_Future is a wrapper for a SandstormHttpBridge_getSandstormApi_Params promised by a client call.
type SandstormHttpBridge_getSandstormApi_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSandstormApi_Params_Future) Struct() (SandstormHttpBridge_getSandstormApi_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSandstormApi_Params{s}, err
}

type SandstormHttpBridge_getSandstormApi_Results struct{ capnp.Struct }

// SandstormHttpBridge_getSandstormApi_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSandstormApi_Results.
const SandstormHttpBridge_getSandstormApi_Results_TypeID = 0xc174fe273bd649ac

func NewSandstormHttpBridge_getSandstormApi_Results(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results{st}, err
}

func NewRootSandstormHttpBridge_getSandstormApi_Results(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results{st}, err
}

func ReadRootSandstormHttpBridge_getSandstormApi_Results(msg *capnp.Message) (SandstormHttpBridge_getSandstormApi_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSandstormApi_Results{root.Struct()}, err
}

func (s SandstormHttpBridge_getSandstormApi_Results) String() string {
	str, _ := text.Marshal(0xc174fe273bd649ac, s.Struct)
	return str
}

func (s SandstormHttpBridge_getSandstormApi_Results) Api() grain.SandstormApi {
	p, _ := s.Struct.Ptr(0)
	return grain.SandstormApi{Client: p.Interface().Client()}
}

func (s SandstormHttpBridge_getSandstormApi_Results) HasApi() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_getSandstormApi_Results) SetApi(v grain.SandstormApi) error {
	if !v.Client.IsValid() {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSandstormApi_Results_List is a list of SandstormHttpBridge_getSandstormApi_Results.
type SandstormHttpBridge_getSandstormApi_Results_List struct{ capnp.List }

// NewSandstormHttpBridge_getSandstormApi_Results creates a new list of SandstormHttpBridge_getSandstormApi_Results.
func NewSandstormHttpBridge_getSandstormApi_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSandstormApi_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_getSandstormApi_Results_List{l}, err
}

func (s SandstormHttpBridge_getSandstormApi_Results_List) At(i int) SandstormHttpBridge_getSandstormApi_Results {
	return SandstormHttpBridge_getSandstormApi_Results{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSandstormApi_Results_List) Set(i int, v SandstormHttpBridge_getSandstormApi_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSandstormApi_Results_List) String() string {
	str, _ := text.MarshalList(0xc174fe273bd649ac, s.List)
	return str
}

// SandstormHttpBridge_getSandstormApi_Results_Future is a wrapper for a SandstormHttpBridge_getSandstormApi_Results promised by a client call.
type SandstormHttpBridge_getSandstormApi_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSandstormApi_Results_Future) Struct() (SandstormHttpBridge_getSandstormApi_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSandstormApi_Results{s}, err
}

func (p SandstormHttpBridge_getSandstormApi_Results_Future) Api() grain.SandstormApi {
	return grain.SandstormApi{Client: p.Future.Field(0, nil).Client()}
}

type SandstormHttpBridge_getSessionContext_Params struct{ capnp.Struct }

// SandstormHttpBridge_getSessionContext_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionContext_Params.
const SandstormHttpBridge_getSessionContext_Params_TypeID = 0xc2a480fa3863a3fa

func NewSandstormHttpBridge_getSessionContext_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Params{st}, err
}

func NewRootSandstormHttpBridge_getSessionContext_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Params{st}, err
}

func ReadRootSandstormHttpBridge_getSessionContext_Params(msg *capnp.Message) (SandstormHttpBridge_getSessionContext_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionContext_Params{root.Struct()}, err
}

func (s SandstormHttpBridge_getSessionContext_Params) String() string {
	str, _ := text.Marshal(0xc2a480fa3863a3fa, s.Struct)
	return str
}

func (s SandstormHttpBridge_getSessionContext_Params) Id() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSessionContext_Params) HasId() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_getSessionContext_Params) IdBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSessionContext_Params) SetId(v string) error {
	return s.Struct.SetText(0, v)
}

// SandstormHttpBridge_getSessionContext_Params_List is a list of SandstormHttpBridge_getSessionContext_Params.
type SandstormHttpBridge_getSessionContext_Params_List struct{ capnp.List }

// NewSandstormHttpBridge_getSessionContext_Params creates a new list of SandstormHttpBridge_getSessionContext_Params.
func NewSandstormHttpBridge_getSessionContext_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionContext_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_getSessionContext_Params_List{l}, err
}

func (s SandstormHttpBridge_getSessionContext_Params_List) At(i int) SandstormHttpBridge_getSessionContext_Params {
	return SandstormHttpBridge_getSessionContext_Params{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSessionContext_Params_List) Set(i int, v SandstormHttpBridge_getSessionContext_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSessionContext_Params_List) String() string {
	str, _ := text.MarshalList(0xc2a480fa3863a3fa, s.List)
	return str
}

// SandstormHttpBridge_getSessionContext_Params_Future is a wrapper for a SandstormHttpBridge_getSessionContext_Params promised by a client call.
type SandstormHttpBridge_getSessionContext_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionContext_Params_Future) Struct() (SandstormHttpBridge_getSessionContext_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionContext_Params{s}, err
}

type SandstormHttpBridge_getSessionContext_Results struct{ capnp.Struct }

// SandstormHttpBridge_getSessionContext_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionContext_Results.
const SandstormHttpBridge_getSessionContext_Results_TypeID = 0xb84ffa3322e48dbd

func NewSandstormHttpBridge_getSessionContext_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results{st}, err
}

func NewRootSandstormHttpBridge_getSessionContext_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results{st}, err
}

func ReadRootSandstormHttpBridge_getSessionContext_Results(msg *capnp.Message) (SandstormHttpBridge_getSessionContext_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionContext_Results{root.Struct()}, err
}

func (s SandstormHttpBridge_getSessionContext_Results) String() string {
	str, _ := text.Marshal(0xb84ffa3322e48dbd, s.Struct)
	return str
}

func (s SandstormHttpBridge_getSessionContext_Results) Context() grain.SessionContext {
	p, _ := s.Struct.Ptr(0)
	return grain.SessionContext{Client: p.Interface().Client()}
}

func (s SandstormHttpBridge_getSessionContext_Results) HasContext() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_getSessionContext_Results) SetContext(v grain.SessionContext) error {
	if !v.Client.IsValid() {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSessionContext_Results_List is a list of SandstormHttpBridge_getSessionContext_Results.
type SandstormHttpBridge_getSessionContext_Results_List struct{ capnp.List }

// NewSandstormHttpBridge_getSessionContext_Results creates a new list of SandstormHttpBridge_getSessionContext_Results.
func NewSandstormHttpBridge_getSessionContext_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionContext_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_getSessionContext_Results_List{l}, err
}

func (s SandstormHttpBridge_getSessionContext_Results_List) At(i int) SandstormHttpBridge_getSessionContext_Results {
	return SandstormHttpBridge_getSessionContext_Results{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSessionContext_Results_List) Set(i int, v SandstormHttpBridge_getSessionContext_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSessionContext_Results_List) String() string {
	str, _ := text.MarshalList(0xb84ffa3322e48dbd, s.List)
	return str
}

// SandstormHttpBridge_getSessionContext_Results_Future is a wrapper for a SandstormHttpBridge_getSessionContext_Results promised by a client call.
type SandstormHttpBridge_getSessionContext_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionContext_Results_Future) Struct() (SandstormHttpBridge_getSessionContext_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionContext_Results{s}, err
}

func (p SandstormHttpBridge_getSessionContext_Results_Future) Context() grain.SessionContext {
	return grain.SessionContext{Client: p.Future.Field(0, nil).Client()}
}

type SandstormHttpBridge_getSavedIdentity_Params struct{ capnp.Struct }

// SandstormHttpBridge_getSavedIdentity_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSavedIdentity_Params.
const SandstormHttpBridge_getSavedIdentity_Params_TypeID = 0x930d8201947c86bf

func NewSandstormHttpBridge_getSavedIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Params{st}, err
}

func NewRootSandstormHttpBridge_getSavedIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Params{st}, err
}

func ReadRootSandstormHttpBridge_getSavedIdentity_Params(msg *capnp.Message) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSavedIdentity_Params{root.Struct()}, err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) String() string {
	str, _ := text.Marshal(0x930d8201947c86bf, s.Struct)
	return str
}

func (s SandstormHttpBridge_getSavedIdentity_Params) IdentityId() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) HasIdentityId() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_getSavedIdentity_Params) IdentityIdBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) SetIdentityId(v string) error {
	return s.Struct.SetText(0, v)
}

// SandstormHttpBridge_getSavedIdentity_Params_List is a list of SandstormHttpBridge_getSavedIdentity_Params.
type SandstormHttpBridge_getSavedIdentity_Params_List struct{ capnp.List }

// NewSandstormHttpBridge_getSavedIdentity_Params creates a new list of SandstormHttpBridge_getSavedIdentity_Params.
func NewSandstormHttpBridge_getSavedIdentity_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSavedIdentity_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_getSavedIdentity_Params_List{l}, err
}

func (s SandstormHttpBridge_getSavedIdentity_Params_List) At(i int) SandstormHttpBridge_getSavedIdentity_Params {
	return SandstormHttpBridge_getSavedIdentity_Params{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSavedIdentity_Params_List) Set(i int, v SandstormHttpBridge_getSavedIdentity_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSavedIdentity_Params_List) String() string {
	str, _ := text.MarshalList(0x930d8201947c86bf, s.List)
	return str
}

// SandstormHttpBridge_getSavedIdentity_Params_Future is a wrapper for a SandstormHttpBridge_getSavedIdentity_Params promised by a client call.
type SandstormHttpBridge_getSavedIdentity_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSavedIdentity_Params_Future) Struct() (SandstormHttpBridge_getSavedIdentity_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSavedIdentity_Params{s}, err
}

type SandstormHttpBridge_getSavedIdentity_Results struct{ capnp.Struct }

// SandstormHttpBridge_getSavedIdentity_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSavedIdentity_Results.
const SandstormHttpBridge_getSavedIdentity_Results_TypeID = 0xc2ba6a7e9ab2e369

func NewSandstormHttpBridge_getSavedIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results{st}, err
}

func NewRootSandstormHttpBridge_getSavedIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results{st}, err
}

func ReadRootSandstormHttpBridge_getSavedIdentity_Results(msg *capnp.Message) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSavedIdentity_Results{root.Struct()}, err
}

func (s SandstormHttpBridge_getSavedIdentity_Results) String() string {
	str, _ := text.Marshal(0xc2ba6a7e9ab2e369, s.Struct)
	return str
}

func (s SandstormHttpBridge_getSavedIdentity_Results) Identity() identity.Identity {
	p, _ := s.Struct.Ptr(0)
	return identity.Identity{Client: p.Interface().Client()}
}

func (s SandstormHttpBridge_getSavedIdentity_Results) HasIdentity() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_getSavedIdentity_Results) SetIdentity(v identity.Identity) error {
	if !v.Client.IsValid() {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSavedIdentity_Results_List is a list of SandstormHttpBridge_getSavedIdentity_Results.
type SandstormHttpBridge_getSavedIdentity_Results_List struct{ capnp.List }

// NewSandstormHttpBridge_getSavedIdentity_Results creates a new list of SandstormHttpBridge_getSavedIdentity_Results.
func NewSandstormHttpBridge_getSavedIdentity_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSavedIdentity_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_getSavedIdentity_Results_List{l}, err
}

func (s SandstormHttpBridge_getSavedIdentity_Results_List) At(i int) SandstormHttpBridge_getSavedIdentity_Results {
	return SandstormHttpBridge_getSavedIdentity_Results{s.List.Struct(i)}
}

func (s SandstormHttpBridge_getSavedIdentity_Results_List) Set(i int, v SandstormHttpBridge_getSavedIdentity_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_getSavedIdentity_Results_List) String() string {
	str, _ := text.MarshalList(0xc2ba6a7e9ab2e369, s.List)
	return str
}

// SandstormHttpBridge_getSavedIdentity_Results_Future is a wrapper for a SandstormHttpBridge_getSavedIdentity_Results promised by a client call.
type SandstormHttpBridge_getSavedIdentity_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSavedIdentity_Results_Future) Struct() (SandstormHttpBridge_getSavedIdentity_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSavedIdentity_Results{s}, err
}

func (p SandstormHttpBridge_getSavedIdentity_Results_Future) Identity() identity.Identity {
	return identity.Identity{Client: p.Future.Field(0, nil).Client()}
}

type SandstormHttpBridge_saveIdentity_Params struct{ capnp.Struct }

// SandstormHttpBridge_saveIdentity_Params_TypeID is the unique identifier for the type SandstormHttpBridge_saveIdentity_Params.
const SandstormHttpBridge_saveIdentity_Params_TypeID = 0xd274ecd8fd2907d0

func NewSandstormHttpBridge_saveIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_saveIdentity_Params{st}, err
}

func NewRootSandstormHttpBridge_saveIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_saveIdentity_Params{st}, err
}

func ReadRootSandstormHttpBridge_saveIdentity_Params(msg *capnp.Message) (SandstormHttpBridge_saveIdentity_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_saveIdentity_Params{root.Struct()}, err
}

func (s SandstormHttpBridge_saveIdentity_Params) String() string {
	str, _ := text.Marshal(0xd274ecd8fd2907d0, s.Struct)
	return str
}

func (s SandstormHttpBridge_saveIdentity_Params) Identity() identity.Identity {
	p, _ := s.Struct.Ptr(0)
	return identity.Identity{Client: p.Interface().Client()}
}

func (s SandstormHttpBridge_saveIdentity_Params) HasIdentity() bool {
	return s.Struct.HasPtr(0)
}

func (s SandstormHttpBridge_saveIdentity_Params) SetIdentity(v identity.Identity) error {
	if !v.Client.IsValid() {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_saveIdentity_Params_List is a list of SandstormHttpBridge_saveIdentity_Params.
type SandstormHttpBridge_saveIdentity_Params_List struct{ capnp.List }

// NewSandstormHttpBridge_saveIdentity_Params creates a new list of SandstormHttpBridge_saveIdentity_Params.
func NewSandstormHttpBridge_saveIdentity_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_saveIdentity_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return SandstormHttpBridge_saveIdentity_Params_List{l}, err
}

func (s SandstormHttpBridge_saveIdentity_Params_List) At(i int) SandstormHttpBridge_saveIdentity_Params {
	return SandstormHttpBridge_saveIdentity_Params{s.List.Struct(i)}
}

func (s SandstormHttpBridge_saveIdentity_Params_List) Set(i int, v SandstormHttpBridge_saveIdentity_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_saveIdentity_Params_List) String() string {
	str, _ := text.MarshalList(0xd274ecd8fd2907d0, s.List)
	return str
}

// SandstormHttpBridge_saveIdentity_Params_Future is a wrapper for a SandstormHttpBridge_saveIdentity_Params promised by a client call.
type SandstormHttpBridge_saveIdentity_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_saveIdentity_Params_Future) Struct() (SandstormHttpBridge_saveIdentity_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_saveIdentity_Params{s}, err
}

func (p SandstormHttpBridge_saveIdentity_Params_Future) Identity() identity.Identity {
	return identity.Identity{Client: p.Future.Field(0, nil).Client()}
}

type SandstormHttpBridge_saveIdentity_Results struct{ capnp.Struct }

// SandstormHttpBridge_saveIdentity_Results_TypeID is the unique identifier for the type SandstormHttpBridge_saveIdentity_Results.
const SandstormHttpBridge_saveIdentity_Results_TypeID = 0xb1b610269c6a2190

func NewSandstormHttpBridge_saveIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results{st}, err
}

func NewRootSandstormHttpBridge_saveIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results{st}, err
}

func ReadRootSandstormHttpBridge_saveIdentity_Results(msg *capnp.Message) (SandstormHttpBridge_saveIdentity_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_saveIdentity_Results{root.Struct()}, err
}

func (s SandstormHttpBridge_saveIdentity_Results) String() string {
	str, _ := text.Marshal(0xb1b610269c6a2190, s.Struct)
	return str
}

// SandstormHttpBridge_saveIdentity_Results_List is a list of SandstormHttpBridge_saveIdentity_Results.
type SandstormHttpBridge_saveIdentity_Results_List struct{ capnp.List }

// NewSandstormHttpBridge_saveIdentity_Results creates a new list of SandstormHttpBridge_saveIdentity_Results.
func NewSandstormHttpBridge_saveIdentity_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_saveIdentity_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return SandstormHttpBridge_saveIdentity_Results_List{l}, err
}

func (s SandstormHttpBridge_saveIdentity_Results_List) At(i int) SandstormHttpBridge_saveIdentity_Results {
	return SandstormHttpBridge_saveIdentity_Results{s.List.Struct(i)}
}

func (s SandstormHttpBridge_saveIdentity_Results_List) Set(i int, v SandstormHttpBridge_saveIdentity_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s SandstormHttpBridge_saveIdentity_Results_List) String() string {
	str, _ := text.MarshalList(0xb1b610269c6a2190, s.List)
	return str
}

// SandstormHttpBridge_saveIdentity_Results_Future is a wrapper for a SandstormHttpBridge_saveIdentity_Results promised by a client call.
type SandstormHttpBridge_saveIdentity_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_saveIdentity_Results_Future) Struct() (SandstormHttpBridge_saveIdentity_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_saveIdentity_Results{s}, err
}

const schema_ac137d236832bb1e = "x\xda\xa4\x93AH\x14Q\x18\xc7\xbf\xef\xcd\x8ec\xa0" +
	"\xe8ccf\x88\x0a2+\x12\x0cK\x8a0\xca\xd5." +
	"\xad\x10\xee\xe8)\xa1\xc3\xb43\xac#\xee:\xed<\xa5" +
	"\"+\x96\xf0 DZ\x09\x15A\x87\xba\x08v\xb0C" +
	"D!V\xe0!\"\x0a\x89\xa8\x83\x87\xa8K\xd0\xad\xdb" +
	"B\xbdx\xb3;\xb3\xb3\xd5!7\xe6\xf6}\xff\xf9~" +
	"\xef}\xff\xff\xeb\x98\xabK\x90\xbdr\xa6\x1d`\xb0\x99" +
	"\xc8u\xdcZ\xb1\xee\xae\xcc\xbc\x9b\x02\xda\x81\x001\x05" +
	"\xa0\xf3\x96\xdaE \xc6\x97\xa7\xce\xdf\xc0B\xe3\xf5R" +
	"GF\xd1\x9aU{\x09`|^\xed\x06\xe4\xd3\x1f\x97" +
	"64^\xcd<\x00\xbaY\xe2[\x9f\xee\x1b\xde>\x19" +
	"_\x00\xc0\xce\xd7j\x01\xe3\x9fT\xf1\xc3\x9a\xaa`|" +
	"NS\x00\xf8\xcc\xb6\x91;;\x9b\x1f-FH\x93Z" +
	"\x9b -]\xf9\xd2\xd2Y\xec\x7f\x1c%\x8dk\x03\x82" +
	"4\xab\x09\xd2B\xf2\xfd\xa1]?\xd9\xf3\xa8`Q\xf3" +
	"\x8f\xf2\xd2\x17\x14\xef\xa5\x0f\x16/\xdd\x7f\x11\x15|\xd5" +
	"\xfa\x84@\xd6\x85\xc0\xf9\xfc\xf0\xf6\x85\x91'U\x82\x1d" +
	"\xba/\xe8\xf1\x05o\x95\xdd?>|c\xabQ\x81\xad" +
	"\xb7\x08\xc1\xa4\xde\x0d<\xfc\xfa\xb8g\xe6,\x8f\x8d\xe5" +
	"\x95l\xfb0cn\xfb\xa9\xbcce\xec=i\xd3\xcd" +
	"\xb9]\x83\xe5f\xf6\x18cno\xa9\x93\xb1YX\xee" +
	"q\x9d\xd6\xee\x94\x997\xb3^8\xa8~]\x83&l" +
	"+i\xd99\xe6\xb0\xb3\xad\xa5A`\xc4\xa4\x18@\x0c" +
	"\x01h\xe3\x10\x80\xd1 \xa1\xa1\x13\xe4NY\x07R\xd2" +
	"\xc2\x06 \xd8\x00\x18R\xe5\x7f\xa4B\x0a\xd1h\x96d" +
	"\x800,\x18\x18BO\x17\x80PG\xc1\x8a\x05\x18\xb8" +
	"IO^\x03BO(H\xc2(a`\x03=>\x0d" +
	"\x84&\x15\x94\xc2\xc5c\x90\x0fzx\x04\x08\xdd\xaf\xf0" +
	"`mX\xde\x1b$\xd0\xaf\xd9\x9e\xe7\xe0X\xee\xe8X" +
	"\x8e\xd9g\x90\x95\xabb/\x18,\x06\x84\xd63'l" +
	"Q\x80&QJ`\x0aq\xfd\xde\x05C\xfcu\x0f\xd8" +
	"^\xd3\xf8(\xab\xd19q\xee\xe0\xd8L\xcc\x1a\x1fe" +
	"\xe8E\xbd\xeb\x050\xea%46\x12\xbc\x98.\xe9\x90" +
	"\xf2\x03\xdf\xd3C[\x12G\x96\x01\x10i\xc4\xc0\xfaZ" +
	"\xf3WBW\xc7\xa6\xa5\x82VL\xd7A\xca_\x11\xb7" +
	"\xedM\xbf\xbd\xfa_\xd8\xea;\x97\xe3Z\x05\xdeT\x01" +
	"K\xce\x9f)\xad\xfdm\x04\xb7\xac\xa2\xf5\xfd\xedu\x00" +
	" \xe5\xfa\x9a1\x7f\xee\xe6\xe5g\xbf_\xb7\xb6\xa4\xa4" +
	"\xcc\xbcbf\xbd\x9a\xd0\xbf\x02\x00\x00\xff\xff%Y\xc6" +
	"\xe9"

func init() {
	schemas.Register(schema_ac137d236832bb1e,
		0x86d490c59f64c564,
		0x930d8201947c86bf,
		0xad678f0d09bdd98a,
		0xb1b610269c6a2190,
		0xb84ffa3322e48dbd,
		0xc174fe273bd649ac,
		0xc2a480fa3863a3fa,
		0xc2ba6a7e9ab2e369,
		0xd274ecd8fd2907d0)
}
